/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Chapter {
  'id' : bigint,
  'title' : string,
  'description' : string,
  'subjectId' : bigint,
  'orderIndex' : bigint,
}
export interface Class {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'grade' : bigint,
}
export interface Lesson {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'chapterId' : bigint,
  'orderIndex' : bigint,
}
export interface Subject {
  'id' : bigint,
  'name' : string,
  'color' : string,
  'description' : string,
  'classId' : bigint,
  'iconName' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addChapter' : ActorMethod<[Chapter], bigint>,
  'addClass' : ActorMethod<[Class], bigint>,
  'addLesson' : ActorMethod<[Lesson], bigint>,
  'addSeedData' : ActorMethod<[], undefined>,
  'addSubject' : ActorMethod<[Subject], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteChapter' : ActorMethod<[bigint], undefined>,
  'deleteClass' : ActorMethod<[bigint], undefined>,
  'deleteLesson' : ActorMethod<[bigint], undefined>,
  'deleteSubject' : ActorMethod<[bigint], undefined>,
  'getAllClasses' : ActorMethod<[], Array<Class>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChaptersBySubject' : ActorMethod<[bigint], Array<Chapter>>,
  'getLesson' : ActorMethod<[bigint], [] | [Lesson]>,
  'getLessonsByChapter' : ActorMethod<[bigint], Array<Lesson>>,
  'getSubjectsByClass' : ActorMethod<[bigint], Array<Subject>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchContent' : ActorMethod<
    [string],
    { 'lessons' : Array<Lesson>, 'chapters' : Array<Chapter> }
  >,
  'updateChapter' : ActorMethod<[bigint, Chapter], undefined>,
  'updateClass' : ActorMethod<[bigint, Class], undefined>,
  'updateLesson' : ActorMethod<[bigint, Lesson], undefined>,
  'updateSubject' : ActorMethod<[bigint, Subject], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];