/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Chapter = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'subjectId' : IDL.Nat,
  'orderIndex' : IDL.Nat,
});
export const Class = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'grade' : IDL.Nat,
});
export const Lesson = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'chapterId' : IDL.Nat,
  'orderIndex' : IDL.Nat,
});
export const Subject = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'color' : IDL.Text,
  'description' : IDL.Text,
  'classId' : IDL.Nat,
  'iconName' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addChapter' : IDL.Func([Chapter], [IDL.Nat], []),
  'addClass' : IDL.Func([Class], [IDL.Nat], []),
  'addLesson' : IDL.Func([Lesson], [IDL.Nat], []),
  'addSeedData' : IDL.Func([], [], []),
  'addSubject' : IDL.Func([Subject], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteChapter' : IDL.Func([IDL.Nat], [], []),
  'deleteClass' : IDL.Func([IDL.Nat], [], []),
  'deleteLesson' : IDL.Func([IDL.Nat], [], []),
  'deleteSubject' : IDL.Func([IDL.Nat], [], []),
  'getAllClasses' : IDL.Func([], [IDL.Vec(Class)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChaptersBySubject' : IDL.Func([IDL.Nat], [IDL.Vec(Chapter)], ['query']),
  'getLesson' : IDL.Func([IDL.Nat], [IDL.Opt(Lesson)], ['query']),
  'getLessonsByChapter' : IDL.Func([IDL.Nat], [IDL.Vec(Lesson)], ['query']),
  'getSubjectsByClass' : IDL.Func([IDL.Nat], [IDL.Vec(Subject)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchContent' : IDL.Func(
      [IDL.Text],
      [
        IDL.Record({
          'lessons' : IDL.Vec(Lesson),
          'chapters' : IDL.Vec(Chapter),
        }),
      ],
      ['query'],
    ),
  'updateChapter' : IDL.Func([IDL.Nat, Chapter], [], []),
  'updateClass' : IDL.Func([IDL.Nat, Class], [], []),
  'updateLesson' : IDL.Func([IDL.Nat, Lesson], [], []),
  'updateSubject' : IDL.Func([IDL.Nat, Subject], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Chapter = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'subjectId' : IDL.Nat,
    'orderIndex' : IDL.Nat,
  });
  const Class = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'grade' : IDL.Nat,
  });
  const Lesson = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'chapterId' : IDL.Nat,
    'orderIndex' : IDL.Nat,
  });
  const Subject = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'color' : IDL.Text,
    'description' : IDL.Text,
    'classId' : IDL.Nat,
    'iconName' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addChapter' : IDL.Func([Chapter], [IDL.Nat], []),
    'addClass' : IDL.Func([Class], [IDL.Nat], []),
    'addLesson' : IDL.Func([Lesson], [IDL.Nat], []),
    'addSeedData' : IDL.Func([], [], []),
    'addSubject' : IDL.Func([Subject], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteChapter' : IDL.Func([IDL.Nat], [], []),
    'deleteClass' : IDL.Func([IDL.Nat], [], []),
    'deleteLesson' : IDL.Func([IDL.Nat], [], []),
    'deleteSubject' : IDL.Func([IDL.Nat], [], []),
    'getAllClasses' : IDL.Func([], [IDL.Vec(Class)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChaptersBySubject' : IDL.Func([IDL.Nat], [IDL.Vec(Chapter)], ['query']),
    'getLesson' : IDL.Func([IDL.Nat], [IDL.Opt(Lesson)], ['query']),
    'getLessonsByChapter' : IDL.Func([IDL.Nat], [IDL.Vec(Lesson)], ['query']),
    'getSubjectsByClass' : IDL.Func([IDL.Nat], [IDL.Vec(Subject)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchContent' : IDL.Func(
        [IDL.Text],
        [
          IDL.Record({
            'lessons' : IDL.Vec(Lesson),
            'chapters' : IDL.Vec(Chapter),
          }),
        ],
        ['query'],
      ),
    'updateChapter' : IDL.Func([IDL.Nat, Chapter], [], []),
    'updateClass' : IDL.Func([IDL.Nat, Class], [], []),
    'updateLesson' : IDL.Func([IDL.Nat, Lesson], [], []),
    'updateSubject' : IDL.Func([IDL.Nat, Subject], [], []),
  });
};

export const init = ({ IDL }) => { return []; };